In [2]:
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [2]:
ls

 Volume in drive C is OS
 Volume Serial Number is 147D-662A

 Directory of C:\Users\Odeyemi Tolutope

30/09/2019  19:54    <DIR>          .
30/09/2019  19:54    <DIR>          ..
22/11/2018  13:45    <DIR>          .anaconda
22/08/2015  17:16    <DIR>          .android
18/12/2018  11:42    <DIR>          .astropy
03/05/2019  17:02    <DIR>          .atom
29/07/2019  11:38    <DIR>          .cache
08/03/2019  10:26    <DIR>          .conda
27/09/2019  11:01                43 .condarc
02/04/2019  08:25    <DIR>          .config
14/12/2018  11:14    <DIR>          .continuum
03/05/2019  09:50    <DIR>          .gem
07/02/2019  20:44                52 .gitconfig
18/12/2018  11:44    <DIR>          .glue
09/01/2019  12:36    <DIR>          .idea
14/01/2019  07:32    <DIR>          .idlerc
30/09/2019  01:26    <DIR>          .ipynb_checkpoints
22/11/2018  13:53    <DIR>          .ipython
05/01/2019  22:29    <DIR>          .jupyter
20/02/2019  09:53    <DIR>          .keras
30/09/2019  01:54

In [3]:
weather= pd.read_csv('./daily_weather.csv')

In [4]:
weather.head(3)

number  air_pressure_9am  air_temp_9am  avg_wind_direction_9am  \
0       0        918.060000     74.822000              271.100000   
1       1        917.347688     71.403843              101.935179   
2       2        923.040000     60.638000               51.000000   

   avg_wind_speed_9am  max_wind_direction_9am  max_wind_speed_9am  \
0            2.080354              295.400000            2.863283   
1            2.443009              140.471548            3.533324   
2           17.067852               63.700000           22.100967   

   rain_accumulation_9am  rain_duration_9am  relative_humidity_9am  \
0                    0.0                0.0              42.420000   
1                    0.0                0.0              24.328697   
2                    0.0               20.0               8.900000   

   relative_humidity_3pm  
0              36.160000  
1              19.426597  
2              14.460000

In [5]:
weather= weather.dropna()

In [6]:
weather.isnull().any()

number                    False
air_pressure_9am          False
air_temp_9am              False
avg_wind_direction_9am    False
avg_wind_speed_9am        False
max_wind_direction_9am    False
max_wind_speed_9am        False
rain_accumulation_9am     False
rain_duration_9am         False
relative_humidity_9am     False
relative_humidity_3pm     False
dtype: bool

In [7]:
clean_data=weather

In [8]:
clean_data['high_humidity_label']=(clean_data['relative_humidity_3pm'] >19.50 )*1
print(clean_data['high_humidity_label'])

0       1
1       0
2       0
3       0
4       1
5       1
6       1
7       1
8       1
9       1
10      1
11      1
12      1
13      1
14      1
15      0
17      1
18      1
19      0
20      0
21      1
22      0
23      1
24      0
25      1
26      1
27      1
28      1
29      1
30      1
       ..
1064    1
1065    1
1067    1
1068    1
1069    1
1070    1
1071    1
1072    1
1073    1
1074    1
1075    0
1076    1
1077    1
1078    0
1079    1
1080    1
1081    0
1082    1
1083    1
1084    1
1085    1
1086    1
1087    1
1088    1
1089    1
1090    1
1091    1
1092    1
1093    1
1094    0
Name: high_humidity_label, Length: 1064, dtype: int32


In [9]:
y=clean_data[['high_humidity_label']]
#y


In [10]:
y

high_humidity_label
0                       1
1                       0
2                       0
3                       0
4                       1
5                       1
6                       1
7                       1
8                       1
9                       1
10                      1
11                      1
12                      1
13                      1
14                      1
15                      0
17                      1
18                      1
19                      0
20                      0
21                      1
22                      0
23                      1
24                      0
25                      1
26                      1
27                      1
28                      1
29                      1
30                      1
...                   ...
1064                    1
1065                    1
1067                    1
1068                    1
1069                    1
1070                    1
1071                    1
1072                    1
1073                    1
1074                    1
1075                    0
1076                    1
1077                    1
1078                    0
1079                    1
1080                    1
1081                    0
1082                    1
1083                    1
1084                    1
1085                    1
1086                    1
1087                    1
1088                    1
1089                    1
1090                    1
1091                    1
1092                    1
1093                    1
1094                    0

[1064 rows x 1 columns]

In [11]:
morning_features = ['air_pressure_9am','air_temp_9am','avg_wind_direction_9am','avg_wind_speed_9am',
        'max_wind_direction_9am','max_wind_speed_9am','rain_accumulation_9am',
        'rain_duration_9am']

In [12]:
X=clean_data[morning_features]

In [13]:
X.head(5)

air_pressure_9am  air_temp_9am  avg_wind_direction_9am  avg_wind_speed_9am  \
0        918.060000     74.822000              271.100000            2.080354   
1        917.347688     71.403843              101.935179            2.443009   
2        923.040000     60.638000               51.000000           17.067852   
3        920.502751     70.138895              198.832133            4.337363   
4        921.160000     44.294000              277.800000            1.856660   

   max_wind_direction_9am  max_wind_speed_9am  rain_accumulation_9am  \
0              295.400000            2.863283                    0.0   
1              140.471548            3.533324                    0.0   
2               63.700000           22.100967                    0.0   
3              211.203341            5.190045                    0.0   
4              136.500000            2.863283                    8.9   

   rain_duration_9am  
0                0.0  
1                0.0  
2               20.0  
3                0.0  
4            14730.0

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
X=X.values
y=y.values

In [16]:
sc = StandardScaler()
X = sc.fit_transform(X)

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.1, random_state=1)

In [18]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
%matplotlib inline

import torch
from torch.utils.data import DataLoader, Dataset

In [20]:
import torch, torch.nn as nn, torch.nn.functional as F
from torch.autograd import Variable
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import torch.utils.data as data_utils

In [21]:
class classifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(8, 16)
        self.fc2 = nn.Linear(16, 18)
        self.fc3 = nn.Linear(18, 20)
        self.fc4 = nn.Linear(20, 24)
        self.fc5 = nn.Linear(24, 1)
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.dropout(x, p=0.25)
        x = F.relu(self.fc3(x))
        x = F.relu(self.fc4(x))
        x = F.sigmoid(self.fc5(x))
        return x

In [22]:
net =classifier().double()

In [23]:
net

classifier(
  (fc1): Linear(in_features=8, out_features=16, bias=True)
  (fc2): Linear(in_features=16, out_features=18, bias=True)
  (fc3): Linear(in_features=18, out_features=20, bias=True)
  (fc4): Linear(in_features=20, out_features=24, bias=True)
  (fc5): Linear(in_features=24, out_features=1, bias=True)
)

In [24]:
X_train = torch.from_numpy(X_train)
Y_train = torch.from_numpy(Y_train).double()

In [25]:
loss_fn = nn.BCELoss()
optimizer = torch.optim.Adam(net.parameters(), lr=1e-3)

In [26]:
training_epochs = 2
minibatch_size = 64

In [27]:
train = data_utils.TensorDataset(X_train, Y_train)
train_loader = data_utils.DataLoader(train, batch_size=minibatch_size, shuffle=True)

In [28]:
for i in range(training_epochs):
    for b, data in enumerate(train_loader, 0):
        inputs, labels = data
        y_pred = net(inputs)
        loss = loss_fn(y_pred, labels)
        
        if b % 100:
            print('Epochs: {}, batch: {} loss: {}'.format(i, b, loss))
        #reset gradients
        optimizer.zero_grad()

        # backward pass
        loss.backward()

        # update weights
        optimizer.step()

C:\Users\Odeyemi Tolutope\Anaconda3\lib\site-packages\torch\nn\functional.py:1350: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


Epochs: 0, batch: 1 loss: 0.6846102624294946
Epochs: 0, batch: 2 loss: 0.6841585787644877
Epochs: 0, batch: 3 loss: 0.6870197732675194
Epochs: 0, batch: 4 loss: 0.6836702405562851
Epochs: 0, batch: 5 loss: 0.6792889537231622
Epochs: 0, batch: 6 loss: 0.679218620487991
Epochs: 0, batch: 7 loss: 0.6777180620757792
Epochs: 0, batch: 8 loss: 0.6804286479017749
Epochs: 0, batch: 9 loss: 0.6665181831688602
Epochs: 0, batch: 10 loss: 0.6928279697048247
Epochs: 0, batch: 11 loss: 0.6864654295077149
Epochs: 0, batch: 12 loss: 0.6698876349652537
Epochs: 0, batch: 13 loss: 0.6749710978349993
Epochs: 0, batch: 14 loss: 0.6659526212052277
Epochs: 1, batch: 1 loss: 0.6596312735588206
Epochs: 1, batch: 2 loss: 0.6547062409165703
Epochs: 1, batch: 3 loss: 0.6626505361798944
Epochs: 1, batch: 4 loss: 0.6626464623402195
Epochs: 1, batch: 5 loss: 0.6537378747103773
Epochs: 1, batch: 6 loss: 0.6663936453853239
Epochs: 1, batch: 7 loss: 0.6576251118797845
Epochs: 1, batch: 8 loss: 0.6632281898962986
Epochs

In [29]:
 y_pred = net(inputs)

In [31]:
ypred

NameError: name 'ypred' is not defined

In [16]:
X.as_matrix(columns=None).copy

C:\Users\Odeyemi Tolutope\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


<function ndarray.copy>

In [17]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
%matplotlib inline

import torch
from torch.utils.data import DataLoader, Dataset


In [22]:
X=X.values
y=y.values

In [23]:
 np.unique(X)

array([0.00000000e+00, 1.20959113e-05, 1.19449698e-03, ...,
       1.58000000e+04, 1.58490000e+04, 1.77040000e+04])

In [24]:
X.columns

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [38]:
from torch.autograd import Variable
from torch.nn import Linear, Module, MSELoss
from torch.optim import SGD
import torch.nn.functional as F
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader

In [41]:
class LinearRegressionModel(nn.Module):

    def __init__(self, input_dim, output_dim):

        super(LinearRegressionModel, self).__init__() 
        # Calling Super Class's constructor
        self.linear = nn.Linear(input_dim, output_dim)
        # nn.linear is defined in nn.Module

    def forward(self, X):
        # Here the forward pass is simply a linear function

        out = self.linear(X)
        return out

input_dim = 8
output_dim = 1
#Steps
#Create instance of model
#Select Loss Criterion
#Choose Hyper Parameters#
model = LinearRegressionModel(input_dim,output_dim)

criterion = nn.MSELoss()# Mean Squared Loss
l_rate = 0.01
optimiser = torch.optim.SGD(model.parameters(), lr = l_rate) #Stochastic Gradient Descent

epochs = 500


In [ ]:
for epoch in range(epochs):

    epoch +=1
    #increase the number of epochs by 1 every time
    inputs = Variable(torch.from_numpy(X_train))
    labels = Variable(torch.from_numpy(y_test))

    #clear grads as discussed in prev post
    optimiser.zero_grad()
    #forward to get predicted values
    outputs = model.forward(inputs)
    loss = criterion(outputs, labels)
    loss.backward()# back props
    optimiser.step()# update the parameters
    print('epoch {}, loss {}'.format(epoch,loss.data[0]))

In [52]:

x_test=torch.from_numpy(X_test.values)
Y_train=torch.from_numpy(y_train.values)
Y_test=torch.from_numpy(y_test.values)

In [58]:
X_train

tensor([[9.1830e+02, 5.5422e+01, 8.9967e+01,  ..., 7.4629e+00, 0.0000e+00,
         0.0000e+00],
        [9.1497e+02, 7.3688e+01, 1.8820e+02,  ..., 3.0646e+00, 0.0000e+00,
         0.0000e+00],
        [9.1684e+02, 5.5274e+01, 5.1700e+01,  ..., 6.2411e+00, 1.0000e-02,
         1.1000e+02],
        ...,
        [9.1517e+02, 5.1170e+01, 2.3530e+02,  ..., 2.4159e+00, 0.0000e+00,
         0.0000e+00],
        [9.1127e+02, 5.9828e+01, 2.1830e+02,  ..., 2.9751e+00, 0.0000e+00,
         0.0000e+00],
        [9.1740e+02, 7.0322e+01, 1.7620e+02,  ..., 7.1358e+00, 5.0000e-02,
         2.7000e+02]], dtype=torch.float64)

In [62]:
model = LinearRegressionModel(input_dim,output_dim)

criterion = nn.MSELoss()# Mean Squared Loss
l_rate = 0.01
optimiser = torch.optim.SGD(model.parameters(), lr = l_rate) #Stochastic Gradient Descent

epochs = 200

NameError: name 'LinearRegressionModel' is not defined

tensor([[1],
        [0],
        [0],
        ...,
        [1],
        [1],
        [0]], dtype=torch.int32)

tensor([[918.0600,  74.8220, 271.1000,  ...,   2.8633,   0.0000,   0.0000],
        [917.3477,  71.4038, 101.9352,  ...,   3.5333,   0.0000,   0.0000],
        [923.0400,  60.6380,  51.0000,  ...,  22.1010,   0.0000,  20.0000],
        ...,
        [916.6000,  71.0960, 189.3000,  ...,   3.8923,   0.0000,   0.0000],
        [912.6000,  58.4060, 172.7000,  ...,   4.7647,   0.0000,   0.0000],
        [921.5300,  77.7020,  97.1000,  ...,   4.4515,   0.0000,   0.0000]],
       dtype=torch.float64)